### ISSUE TITLE
Add a page for tech article summarization

### ISSUE THREAD

**Issue by kiseki1011** [seungki1011/seungki1011.github.io#1]
## Description
---
1. Use the OpenAI api to summarize posts or articles from reddit and tech journals.
2. Automatically post them on the page using cron and bash script.

## TODO
---
- [x] Get top posts from ML related sub-reddits
- [ ] Use the gpt api to summarize the posts
- [x] Setup automated workflow

## 2023-9-18
* crontab ```30 2 * * * ```

## 2023-11-13
* 이미 요약되어 있는 포스트를 다시 가져와서 요약하는건 의미가 없는 것 같다.
* 그냥 직접가서 내용을 찾고 읽는게 더 도움이 되는 것 같아서 reddit page는 지울 예정.
